### PR TITLE
submitted monument-react-refactoring hw week 6

### PR DESCRIPTION
**Pull request by lvmor**

### CODE REVIEW

**Comment by lvmor** [comment]
submitted react-counters-master hw week 6

**Comment by lvmor** [comment]
submitted react-giphy-lab week 6

**Comment by lvmor** [comment]
submitted personal-api week 4

**Comment by lvmor** [comment]
created component for post functionality

**Comment by DaltonHart** [comment]
Loving all the commits and notations you are leaving. Great job!

**Pull request merged**
