### PR TITLE
week8 Monday night Capital State Game in Python3

### PR DESCRIPTION
**Pull request by heggy231**

### CODE REVIEW

**Comment by heggy231** [comment]
adding week 8 Tuesday night codebar assignment

**Comment by heggy231** [comment]
week8 Wed night hw Carmen postgres sql postico (attempt upto 6)

**Comment by heggy231** [comment]
Thursday HW on making Reddit post with Flask and peewee
- currently app crashes when I click on post/<id> route to create a comment.

**Comment by heggy231** [comment]
Weekend refactor todo react-flask hw (priority gets passed to Flask backend)

**Comment by DaltonHart** [comment]
Keep up the great job Heggy.

**Pull request merged**
